/**
 * pom-generator.ts
 * Analyzes the current page and returns CSS + XPath locators.
 * Output is plain text for inline display — no files written.
 *
 * Resilience scoring:
 *   data-testid/data-cy/data-qa  → 95
 *   aria-label                   → 90
 *   stable id                    → 85
 *   label[for] association       → 80
 *   name attribute               → 75
 *   placeholder                  → 70
 *   type + semantic tag          → 60
 *   class-based CSS              → 40
 *   nth-child / position-based   → 20 (flagged ⚠)
 */
import { Page } from 'playwright';

export interface LocatorEntry {
  name: string;
  css: string;
  xpath: string;
  resilience: number;
  fragile: boolean;
}

export async function generateLocators(page: Page): Promise<LocatorEntry[]> {
  const raw: LocatorEntry[] = await page.evaluate(() => {
    const INTERACTIVE_SELECTORS =
      'input, button, a[href], select, textarea, [role="button"], ' +
      '[role="link"], [role="textbox"], [role="checkbox"], [role="combobox"], ' +
      '[role="tab"], [role="menuitem"], [role="switch"]';

    function isVisible(el: Element): boolean {
      const r = (el as HTMLElement).getBoundingClientRect();
      const style = window.getComputedStyle(el);
      return r.width > 0 && r.height > 0 &&
        style.visibility !== 'hidden' &&
        style.display !== 'none' &&
        style.opacity !== '0';
    }

    function toSnakeCase(str: string): string {
      return str.toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_+|_+$/g, '').slice(0, 40) || 'element';
    }

    function isAutoGeneratedId(id: string): boolean {
      return /^(react-|ember|__|\d|uid|comp|el-)/.test(id) || /\d{4,}/.test(id);
    }

    function escAttr(v: string): string {
      return v.replace(/'/g, "\\'").replace(/"/g, '\\"');
    }

    /** Build a minimal unique CSS path for the element as fallback */
    function buildCssPath(el: HTMLElement): string {
      const parts: string[] = [];
      let cur: HTMLElement | null = el;
      while (cur && cur !== document.body) {
        const tag = cur.tagName.toLowerCase();
        const siblings = cur.parentElement
          ? Array.from(cur.parentElement.children).filter(c => c.tagName === cur!.tagName)
          : [];
        const part = siblings.length > 1
          ? `${tag}:nth-of-type(${siblings.indexOf(cur) + 1})`
          : tag;
        parts.unshift(part);
        cur = cur.parentElement as HTMLElement | null;
        if (parts.length >= 4) break;
      }
      return parts.join(' > ');
    }

    /** Build XPath for the element as fallback */
    function buildXPath(el: HTMLElement): string {
      const parts: string[] = [];
      let cur: HTMLElement | null = el;
      while (cur && cur !== document.body) {
        const tag = cur.tagName.toLowerCase();
        const siblings = cur.parentElement
          ? Array.from(cur.parentElement.children).filter(c => c.tagName === cur!.tagName)
          : [];
        const part = siblings.length > 1
          ? `${tag}[${siblings.indexOf(cur) + 1}]`
          : tag;
        parts.unshift(part);
        cur = cur.parentElement as HTMLElement | null;
        if (parts.length >= 4) break;
      }
      return '//' + parts.join('/');
    }

    const seen = new Set<string>();
    const entries: any[] = [];

    document.querySelectorAll<HTMLElement>(INTERACTIVE_SELECTORS).forEach(el => {
      if (!isVisible(el)) return;

      const tag = el.tagName.toLowerCase();
      const type = el.getAttribute('type') ?? '';
      const testId = el.getAttribute('data-testid') ?? el.getAttribute('data-cy') ?? el.getAttribute('data-qa') ?? '';
      const ariaLabel = el.getAttribute('aria-label') ?? '';
      const id = el.getAttribute('id') ?? '';
      const labelEl = id ? document.querySelector<HTMLElement>(`label[for="${id}"]`) : null;
      const labelText = labelEl?.innerText?.trim() ?? '';
      const innerText = el.innerText?.trim().slice(0, 60) ?? '';
      const placeholder = el.getAttribute('placeholder') ?? '';
      const name = el.getAttribute('name') ?? '';
      const cls = Array.from(el.classList).filter(c => !/\d{3,}/.test(c)).slice(0, 2).join('.');

      let css = '';
      let xpath = '';
      let resilience = 0;
      let fragile = false;
      let humanName = '';

      if (testId) {
        const attr = el.getAttribute('data-testid') ? 'data-testid' : el.getAttribute('data-cy') ? 'data-cy' : 'data-qa';
        css = `[${attr}="${escAttr(testId)}"]`;
        xpath = `//${tag}[@${attr}="${escAttr(testId)}"]`;
        resilience = 95;
        humanName = toSnakeCase(testId);
      } else if (ariaLabel) {
        css = `${tag}[aria-label="${escAttr(ariaLabel)}"]`;
        xpath = `//${tag}[@aria-label="${escAttr(ariaLabel)}"]`;
        resilience = 90;
        humanName = toSnakeCase(ariaLabel);
      } else if (id && !isAutoGeneratedId(id)) {
        css = `#${CSS.escape(id)}`;
        xpath = `//${tag}[@id="${escAttr(id)}"]`;
        resilience = 85;
        humanName = toSnakeCase(id);
      } else if (labelText) {
        css = id ? `#${CSS.escape(id)}` : `${tag}[name="${escAttr(name || id)}"]`;
        xpath = `//label[normalize-space()="${escAttr(labelText)}"]/following-sibling::${tag}[1]`;
        resilience = 80;
        humanName = toSnakeCase(labelText) + (tag === 'input' ? '_input' : '');
      } else if (name) {
        css = `${tag}[name="${escAttr(name)}"]`;
        xpath = `//${tag}[@name="${escAttr(name)}"]`;
        resilience = 75;
        humanName = toSnakeCase(name);
      } else if (placeholder) {
        css = `${tag}[placeholder="${escAttr(placeholder)}"]`;
        xpath = `//${tag}[@placeholder="${escAttr(placeholder)}"]`;
        resilience = 70;
        humanName = toSnakeCase(placeholder) + '_input';
      } else if (type && (tag === 'input' || tag === 'button')) {
        css = `${tag}[type="${type}"]`;
        xpath = `//${tag}[@type="${type}"]`;
        resilience = 60;
        humanName = toSnakeCase(type + '_' + tag);
      } else if (tag === 'button' && innerText) {
        const t = escAttr(innerText);
        css = `button`;
        xpath = `//button[normalize-space()="${t}"]`;
        resilience = 60;
        humanName = toSnakeCase(innerText) + '_button';
      } else if (tag === 'a' && innerText) {
        const t = escAttr(innerText);
        css = `a`;
        xpath = `//a[normalize-space()="${t}"]`;
        resilience = 60;
        humanName = toSnakeCase(innerText) + '_link';
      } else if (cls) {
        css = `${tag}.${cls.replace(/\./g, '.')}`;
        xpath = `//${tag}[contains(@class,"${cls.split('.')[0]}")]`;
        resilience = 40;
        fragile = true;
        humanName = toSnakeCase(cls.split('.')[0] || tag);
      } else {
        css = buildCssPath(el);
        xpath = buildXPath(el);
        resilience = 20;
        fragile = true;
        humanName = toSnakeCase(innerText || tag) + '_el';
      }

      // Deduplicate by CSS
      if (!css || seen.has(css)) return;
      seen.add(css);

      entries.push({ name: humanName, css, xpath, resilience, fragile });
    });

    return entries;
  });

  return raw.sort((a, b) => b.resilience - a.resilience);
}

export function formatLocators(entries: LocatorEntry[], url: string, title: string): string {
  const header = `Page: ${title} | ${url}\n`;
  const lines = entries.map(e => {
    const flag = e.fragile ? ' ⚠' : '';
    return (
      `${e.name.padEnd(28)} CSS: ${e.css.padEnd(50)} [${e.resilience}]${flag}\n` +
      `${''.padEnd(28)}      XPath: ${e.xpath}`
    );
  });
  return header + '\n' + lines.join('\n\n');
}

export async function runCli() {
  const { chromium } = require('playwright');
  const url = process.argv[2] ?? 'https://example.com';
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto(url, { waitUntil: 'networkidle' });
  const entries = await generateLocators(page);
  console.log(formatLocators(entries, page.url(), await page.title()));
  await browser.close();
}

if (require.main === module) {
  runCli().catch(console.error);
}
